language: node_js
node_js:
  - '12.13.0'
branches:
  only:
    - master
    - build
cache:
  yarn: true
before_install:
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
script:
  - git config --global user.name "travis"
  - git config --global user.email "travis@bastienpaul.fr"
  - yarn && yarn deploy
